Makefile and first pass
g0v/labor-standards-tw pull request #9
Opened 2017-04-14 15:42 UTC by YauHsien

加上 Makefile 並指出測試指令
解 pay.test.js 第一行測試
將 references 拉到獨立檔案

2017-04-14 15:50 UTC, YauHsien commented
我所安裝的 Chai 會遭遇問題：指出 let 詞彙不能用在非 strict 環境，因此將 let 都換為 var 則可以跑過。

2017-04-14 16:55 UTC, YauHsien commented
試將條文列入 doc/labor_standards_act.js 與 legal_interpretations.js

不過，條文應該要抓取並放到適當的資料儲存體。

2017-04-15 00:04 UTC, yurenju commented
@YauHsien 謝謝你的 PR! 我有些疑問跟覺得需要修改的地方會寫在下一個 review comment 裡面。

2017-04-15 00:19 UTC, yurenju requested changes
謝謝你的 PR, 覺得把法條都整理到一個檔案是個好主意，請你把需要修改的地方改善一下，謝謝！

2017-04-15 00:19 UTC, yurenju commented on Makefile
> +	npm test
為什麼需要 `Makefile` 呢？目前我比較常用 npm 作為簡易的流程相依控制，如使用 `postinstall`, `preinstall` 等，雖然不比 Makefile 的流程控制功能這麼完善，不過這樣應該在這個專案應該就足夠了。

2017-04-15 00:19 UTC, yurenju commented on src/doc/legal_interpretations.js
> +	ref_lsa: 24
這邊可能會參考不只有勞基法，而且可能參考多個法令，我覺得用以下規則會比較好：
```javascript
{ reference: ['LSA-24'], ... }
```

2017-04-15 00:19 UTC, yurenju commented on src/index.js
> +	return obj;
這邊 `var` 應該要使用 `let`，如果你的環境不會過，可能是 node.js 要改用 6.x 的版本。另外縮排也需要處理一下，縮排跟 let 修改完後應該要長這樣：

```javascript
module.exports = {
  hourlySalary(monthly) {
    let lint = require('./doc/legal_interpretations.js');
    let obj = {
      reference: [lint[0],
      value: monthly / 30 / 8,
      rest: []
    };
  }
}
```

2017-04-15 00:19 UTC, yurenju commented on test/integration/pays.test.js
> +      var result = std.hourlySalary(36000);
以下所有改用 `var` 的請改回 `let`，`var` 是 function scope, `let` 是 block scope，用起來會比較容易理解，無法預期的狀況也會比較少。

2017-04-15 00:46 UTC, YauHsien commented
使用 Makefile 只是因為我個人普遍的習慣，而對一份專案普遍的操作指令與軟體版本，都可以透過 Makefile 所寫下的，做為簡便的提示。

2017-04-15 00:50 UTC, YauHsien commented on src/index.js
> +	return obj;
排版上一般會有基本的困難，是有些編輯工具太好用了，例如我用的 emacs 在 JavaScript 模式，隨便打任何一行就自動幫忙以 4 空格為單位縮排。還要特別設定才行。

2017-04-15 00:56 UTC, YauHsien commented on src/doc/legal_interpretations.js
> +	ref_lsa: 24
看系統的內部表達。 reference: ['LSA-24'] 是幾乎已經外部可用的東西，但是當你要處理這個詞彙時，得由 'LSA-' 解讀出它是指勞基法，而非函釋，這牽涉到 'LSA-24' 這個詞彙不是純量詞彙，而需要再 parse 一次，才能聯絡到其他的系統資料。而我的處理只是取內部表達與純量的用法而已。

2017-04-15 00:57 UTC, YauHsien commented on Makefile
> +	npm test
彼此不相衝突。 Makefile 只是個獨立的工具，沒有排擠到 npm 的使用空間。

2017-04-15 01:35 UTC, yurenju commented
我覺得 Makefile 不是很必要，使用 npm 作為流程控制就好了。可以請你再下一個 commit 把它移除嗎？

2017-04-15 01:36 UTC, YauHsien commented
你想多了，不需要談 Makefile 是不是很必要。頂多永遠不把 Makefile commit 即可。

2017-04-15 01:51 UTC, yurenju commented on src/doc/legal_interpretations.js
> +	ref_lsa: 24
你說的也有道理，那如果這樣的函釋中參照了兩個法律要如何表示呢？

![image](https://cloud.githubusercontent.com/assets/22155/25059845/ebf5de92-21c0-11e7-90ba-93249e0a8d6c.png)


https://laws.mol.gov.tw/FLAW/FLAWDOC03.aspx?datatype=etype&lc1=%5bc%5d%E5%8B%9E%E5%8B%95%E5%9F%BA%E6%BA%96%E6%B3%95%2c39&cnt=41&recordno=2

2017-04-15 01:52 UTC, yurenju commented on src/index.js
> +	return obj;
我今天晚點會把 eslint 加上去，下次 git commit 的時候就會自動檢查了。

2017-04-15 01:53 UTC, yurenju commented
總之如果改好了之後我會直接 merge pull request，到時候 Makefile 不包含在裡面就好了。

2017-04-15 02:25 UTC, yurenju commented on src/index.js
> +	return obj;
pre-commit 有點麻煩，我先把 eslint 跟 travis-ci 先設定好，這樣至少開 pr 的時候會在 travis 上跑 lint 檢查。

2017-04-15 13:53 UTC, YauHsien commented
那以你這樣的指教方式，是否將來有人加了 bat 檔， .sh 檔， travis.yml 檔等等，這些很普遍的東西，都要照樣指教一次？只准人用默認的方式使用 npm 工具組（而且若跑起來有問題，你還要毫無來由去說是不是對方 node 版本有問題），而不能有其他的明確寫作的文字檔？

只去想這種不重要的事情，實在讓人感到毫無興趣欸。

2017-04-15 13:57 UTC, YauHsien commented on src/doc/legal_interpretations.js
> +	ref_lsa: 24
我是覺得，有經驗的人都會知道同一個資料有外部表達法與內部表達法。都已經說用純量 id 表示了，你卻還想著像這個案例要如何表示、像那個案例要如何表示，而不理解憑著 id 與對於 id 的分類概念就可以在內部做妥善的關聯了，你懂軟體工程嗎？

2017-04-15 14:21 UTC, yurenju commented on src/doc/legal_interpretations.js
> +	ref_lsa: 24
我只是客氣地跟你說你說的也有道理，但是我想知道如果是兩個不同法律的狀況怎麼處理。如果知道怎麼處理，用你提的方法看起來也不錯。我或許軟體工程懂的沒你多，但是態度到沒你那麼嗆。

2017-04-15 14:25 UTC, yurenju commented
可能是因為這個專案才剛開始，所以很多環境設定沒寫得很明確。看到你沒辦法用 `let` 才想到我沒在 README.md 提及這個專案要用 node.js 6，今早也加進去 README 了。

至於每個專案使用的工具集都會有所不同，我覺得就跟 coding style 一樣大家都會有所偏好，如果大家都用不同的工具都 commit 進來，多了之後我覺得也不是什麼不重要的事情。

保持使用的工具集不要太發散，提醒 contributor 的 code 與環境可能有什麼問題都是一個 reviewer 原本就該做的事情，我不覺得這些是不重要的事情，也不是什麼毫無來由的發言。

2017-04-15 14:48 UTC, yurenju commented
我後來想想可能也是大家平常工作的方法比較不同。

我之前工作的經驗同事在 review 我的 patch 時通常會給很多意見，也會有許多提問想知道程式為什麼會用這樣的方式。所以我在 review 時如果遇到什麼疑問或是覺得有什麼要改的也都會直接提出。

如果你覺得我冒犯到你，我覺得可能是工作經驗不同導致的誤會。如果你對這樣 review 的流程有什麼意見，也歡迎提出，或許我們可以找到比較好的溝通合作方式。

2017-04-15 15:06 UTC, YauHsien commented
請你搞清楚。當我打 npm test 或 node ./node_modeuls/mocha/bin/mocha --use_strict test/*/*.js 之後，它回報的訊息叫做 SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside 。但你卻在說 let 與 var 是不同的 block scope ，要用 6 版以上的 node 來跑。

這樣的情況代表你自己連一開始試著跑一下都沒有。首先 block 與 scope 在 node.js 所指是不同的東西。再者，對程式語言有概念的人都知道，所謂語法錯誤，不會因為你升級了一個版本之後，本來語法上不能用 let 突然就跑 let 。而且， index.js 裏頭 require('chai") 是你寫的，這就代表你也沒有去查看 Chai 的 issue 裏頭對於 let 不能跑有什麼樣的討論。

你放著實際的程式不能跑，而瞎扯說 let 是 block 相對於 var 會有比較少的問題，那是根本找碴：別人可不是為了製造更多問題而來使用 var 。本人為了試著讓第一個測試案例可以通過，只是先在 emacs 上敲個 M-Shift-% let -> var 而已，結果就雞雞歪歪個一堆，自己也不去試一試，那你到底想怎樣？要別人貢獻程式碼給你嗎？滾吧。

2017-04-15 15:10 UTC, yurenju commented
![image](https://cloud.githubusercontent.com/assets/22155/25064622/99eeb324-2230-11e7-89fd-c5be1ee7153d.png)

![image](https://cloud.githubusercontent.com/assets/22155/25064625/afc9a1a4-2230-11e7-8489-fecb37a4c6cc.png)

2017-04-15 15:25 UTC, YauHsien commented
你錯了。現階段你連要寫什麼，系統模型都還沒收斂，就在講工具不要發散，想要綁死誰嗎。那麼你還會有多少隱含的規矩，要別人接受？

2017-04-15 15:26 UTC, YauHsien commented on src/doc/legal_interpretations.js
> +	ref_lsa: 24
那我也只是不客氣跟你講說，基本的資料結構都還沒定出來，你就在挑毛病是在挑什麼鬼？

2017-04-15 15:27 UTC, YauHsien commented
太難相處，退出。

2017-04-15 15:27 UTC, closed without merging

2017-04-15 15:28 UTC, yurenju commented
每個專案都有他的開發風格與方式，如果你覺得我真的無法溝通，我可以關掉這個 pull request，我們如果有緣的話在別的專案一起工作吧。